plugins {
    id "java-library"
    id "com.vanniktech.maven.publish" version "0.34.0"
}

group "${groupIdPrefix}.com.google.cloud.verticals.foundations.dataharmonization.plugins.harmonization"
//
//repositories {
//    mavenCentral()
//}

dependencies {
    // TODO(): Set up versioning
    api group: "${groupIdPrefix}.com.google.cloud.verticals.foundations.dataharmonization", name: "runtime"

    implementation group: "com.google.auto.value", name: "auto-value-annotations", version: "1.7.4"
    annotationProcessor group: "com.google.auto.value", name: "auto-value", version: "1.7.4"

    if (gradle.ext.has("annotationProcessorExists") && gradle.ext.annotationProcessorExists){
        annotationProcessor ("${groupIdPrefix}.com.google.cloud.verticals.foundations.dataharmonization:annotation_processor")
    }

    // TODO(): Set up versioning
    testImplementation group: "${groupIdPrefix}.com.google.cloud.verticals.foundations.dataharmonization", name: "testutil"
    testImplementation "junit:junit:4.13"
    testImplementation group: "org.mockito", name: "mockito-core", version: "3.7.7"
    testImplementation group: 'com.google.truth', name: 'truth', version: '1.0.1'
}

repositories {
    mavenCentral()
    maven {
        name = "CentralSnapshots"
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
    }
    maven {
        name = "GitHubSEPackages"
        url = uri("https://maven.pkg.github.com/ShahimEssaid/m2")
    }
}


import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar


mavenPublishing {
    publishToMavenCentral()
    configure(new JavaLibrary(new JavadocJar.None(), true))
}

publishing {
    repositories {
        maven {
            name = "GitHubSEPackages"
            url = uri("https://maven.pkg.github.com/ShahimEssaid/m2")
            credentials(PasswordCredentials)
        }
    }

}

