plugins {
    id 'java-library'
    id 'idea'
    id 'com.vanniktech.maven.publish' version '0.34.0'
}

// SE: change group to allow publishing to OSSRH
group "${groupIdPrefix}.com.google.cloud.verticals.foundations.dataharmonization"

repositories {
    mavenCentral()
}

dependencies {
    api project(":proto")
    api project(":runtime")
    implementation group: 'com.google.guava', name: 'guava', version: "${guavaVersion}"
    implementation group: 'junit', name: 'junit', version: '4.12'
    implementation group: 'org.mockito', name: 'mockito-core', version: '3.7.7'
    implementation group: 'commons-io', name: 'commons-io', version: '2.6'
}


repositories {
    mavenCentral()
    maven {
        name = "CentralSnapshots"
        url = uri("https://central.sonatype.com/repository/maven-snapshots/")
    }
    maven {
        name = "GitHubSEPackages"
        url = uri("https://maven.pkg.github.com/ShahimEssaid/m2")
    }
}




pluginManager.withPlugin("java") {
    java {
        withSourcesJar()
//            withJavadocJar()
    }
}


import com.vanniktech.maven.publish.JavaLibrary
import com.vanniktech.maven.publish.JavadocJar


mavenPublishing {
    publishToMavenCentral()
    configure(new JavaLibrary(new JavadocJar.None(), true))
}

publishing {
    repositories {
        maven {
            name = "GitHubSEPackages"
            url = uri("https://maven.pkg.github.com/ShahimEssaid/m2")
            credentials(PasswordCredentials)
        }
    }
}
